### ISSUE TITLE
Fix Anitya ID

### ISSUE THREAD

**Issue by plata** [flathub/org.kde.telly-skout#4]
The ID was meant only as a placeholder because Telly Skout is not listed in release-monitoring.org. Someone (can't recall who) said that they wanted to create an entry for Plasma Mobile Gear which should be used by all apps packaged as part of it (they don't have individual versions). However, I still cannot find it.

Does anyone know if this has happened or can create such entry? We need the same for KDE Gear as well.

**Comment by travier** [comment]
Hum, I vaguely recall promising to do it but I did not get to in the end. I think you should be able to do it as well.

**Comment by plata** [comment]
Is it something I should just do (I somehow don't feel like I'm the authority for it)? Or does it require an official decision (especially when it comes to KDE Gear)? Should maybe @pointedstick by involved?

**Comment by tsdgeos** [comment]
Honestly i don't see a problem in keeping using the kasts one if we know kasts and telly-skout get released at the same time

**Comment by travier** [comment]
There is nothing that formal here. It's just a tool to track new releases.

As @tsdgeos said, using the Kast one is also perfectly fine if the release schedules are aligned.

**Comment by plata** [comment]
Fixed in #8.
